version: "3"
 
services:
  next-app:
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-test-belqzc-next-app-1.rule=Host(`ivanserver.me`)"
      - "traefik.http.routers.dashboard-test-belqzc-next-app-1.entrypoints=websecure"
      - "traefik.http.routers.dashboard-test-belqzc-next-app-1.tls.certResolver=letsencrypt"
      - "traefik.http.services.dashboard-test-belqzc-next-app-1.loadbalancer.server.port=3000"
networks:
  dokploy-network:
    external: true
